### ISSUE TITLE
panic: runtime error when using nilnil ./...

### ISSUE THREAD

**Issue by ljw7630** [Antonboom/nilnil#29]
go version: go version go1.22.1 darwin/arm64
nilnil version: [v0.1.7](https://github.com/Antonboom/nilnil/releases/tag/v0.1.7)

command:  nilnil ./...

error message:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1004baac4]

goroutine 3 [running]:
go/types.(*Checker).handleBailout(0x14000356400, 0x1400158bb98)
        /opt/homebrew/opt/go/libexec/src/go/types/check.go:367 +0x9c
panic({0x100693d80?, 0x100897ca0?})
        /opt/homebrew/opt/go/libexec/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x1006ea5e8, 0x10089b8a0})
        /opt/homebrew/opt/go/libexec/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
        /opt/homebrew/opt/go/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x1006ea5e8?, 0x10089b8a0?})
        /opt/homebrew/opt/go/libexec/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x1006eb928, 0x1008906f0}, 0x14000356400, 0x10089b8a0, 0x1400158b2e8)
        /opt/homebrew/opt/go/libexec/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x14000356400, 0x140015a7c00, 0x10089b8a0)
        /opt/homebrew/opt/go/libexec/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x14000356400, 0x140015a7c00, {0x1006ea5e8, 0x10089b8a0})
        /opt/homebrew/opt/go/libexec/src/go/types/expr.go:375 +0x304
go/types.(*Checker).assignment(0x14000356400, 0x140015a7c00, {0x1006ea5e8, 0x10089b8a0}, {0x1005e6e4c, 0x14})
        /opt/homebrew/opt/go/libexec/src/go/types/assignments.go:52 +0x23c
go/types.(*Checker).initConst(0x14000356400, 0x14000e6aae0, 0x140015a7c00)
        /opt/homebrew/opt/go/libexec/src/go/types/assignments.go:126 +0x274
go/types.(*Checker).constDecl(0x14000356400, 0x14000e6aae0, {0x1006eab88, 0x1400051e220}, {0x1006eaeb8, 0x140013260f0}, 0x0)
        /opt/homebrew/opt/go/libexec/src/go/types/decl.go:490 +0x250
go/types.(*Checker).objDecl(0x14000356400, {0x1006ee138, 0x14000e6aae0}, 0x0)
        /opt/homebrew/opt/go/libexec/src/go/types/decl.go:191 +0x84c
go/types.(*Checker).packageObjects(0x14000356400)
        /opt/homebrew/opt/go/libexec/src/go/types/resolver.go:693 +0x468
go/types.(*Checker).checkFiles(0x14000356400, {0x140009f9500, 0xb, 0xb})
        /opt/homebrew/opt/go/libexec/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
        /opt/homebrew/opt/go/libexec/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x1400010e000, 0x140002278f0)
        /Users/jinwu.li/go/pkg/mod/golang.org/x/tools@v0.12.0/go/packages/packages.go:1058 +0x8cc
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /Users/jinwu.li/go/pkg/mod/golang.org/x/tools@v0.12.0/go/packages/packages.go:854 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /opt/homebrew/opt/go/libexec/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /Users/jinwu.li/go/pkg/mod/golang.org/x/tools@v0.12.0/go/packages/packages.go:842 +0x50
golang.org/x/tools/go/packages.(*loader).refine.func2(0x0?)
        /Users/jinwu.li/go/pkg/mod/golang.org/x/tools@v0.12.0/go/packages/packages.go:777 +0x30
created by golang.org/x/tools/go/packages.(*loader).refine in goroutine 1
        /Users/jinwu.li/go/pkg/mod/golang.org/x/tools@v0.12.0/go/packages/packages.go:776 +0xaa4
```

**Comment by Antonboom** [comment]
Hi!

Could you provide reproducible example of Go code with which you run linter?

Thanks

**Comment by ljw7630** [comment]
Hi, my guess it's something to do with binary compatibility between `golang`, `nilnil` and `golang.org/x/tools`. it nothing to do with Go code under examined. 

i create very simple repo: https://github.com/ljw7630/go-bug-reproduce
and if I run `nilnil ./...` using my Apple M1 macbook, it panics

**Comment by Antonboom** [comment]
@ljw7630 could you repeat this?

```
$ cd /tmp/go-bug-reproduce
$ rm -rf $(which nilnil)
$ nilnil ./...
zsh: command not found: nilnil
```

```
$ go env
GO111MODULE='on'
GOARCH='arm64'
GOBIN='/Users/anthony/golang_workspace/bin'
GOCACHE='/Users/anthony/Library/Caches/go-build'
GOENV='/Users/anthony/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/anthony/golang_workspace/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/anthony/golang_workspace'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/tmp/go-bug-reproduce/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/6t/v80c8sfs5zqf38b2yhzq592h0000gn/T/go-build1952573084=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

```
$ go install github.com/Antonboom/nilnil@latest
go: downloading github.com/Antonboom/nilnil v0.1.8
```

```
$ nilnil ./...
/tmp/go-bug-reproduce/main.go:10:3: return both the `nil` error and invalid value: use a sentinel error instead
```

**Comment by ljw7630** [comment]
it works, thank you
